baseURL = 'https://handbook.osc.to/'
languageCode = 'en-us'
title = 'The Open Science Community Torino Handbook'

defaultContentLanguage = "en"

[languages]
    [languages.en]
        languageName = "English"
        weight = 1
    [languages.it]
        languageName = "Italiano"
        weight = 2

# The English content is used for English pages
[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'en'

# The Italian content is used for Italian pages
[[module.mounts]]
source = 'content/it'
target = 'content'
lang = 'it'

# The English content is used for Italian pages
# if the italian correspondence is missing
[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'it'

[module]
    [[module.imports]]
        path = "github.com/imfing/hextra"
        disable = false

[[menu.main]]
name = "Documentation"
pageRef = "/docs"
weight = 1

[[menu.main]]
name = "Search"
weight = 2

  [menu.main.params]
  type = "search"

[[menu.main]]
name = "GitHub"
weight = 3
url = "https://github.com/OSCTorino/handbook"

  [menu.main.params]
  icon = "github"

