baseURL = 'https://handbook.osc.to/'
languageCode = 'en-us'
title = 'The OSC Torino Handbook'

defaultContentLanguage = "en"

[languages]
    [languages.en]
        languageName = "English"
        weight = 1
    [languages.it]
        languageName = "Italiano"
        weight = 2

# The English content is used for English pages
[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'en'

# The Italian content is used for Italian pages
[[module.mounts]]
source = 'content/it'
target = 'content'
lang = 'it'

# The English content is used for Italian pages
# if the italian correspondence is missing
[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'it'

# The Italian content is used for English pages
# if the english correspondence is missing
[[module.mounts]]
source = 'content/it'
target = 'content'
lang = 'en'

[module]
    [[module.imports]]
        path = "github.com/imfing/hextra"
        disable = false

[[menu.main]]
name = "Data Management"
pageRef = "/data_management"
weight = 1

[[menu.main]]
name = "Data Analysis"
pageRef = "/data_analysis"
weight = 2

[[menu.main]]
name = "Open Science"
pageRef = "/open_science"
weight = 3

[[menu.main]]
name = "About"
url = "https://osc-international.com/osc-torino/"
weight = 4

[[menu.main]]
name = "Search"
weight = 5

  [menu.main.params]
  type = "search"

[[menu.main]]
name = "GitHub"
weight = 6
url = "https://github.com/OSCTorino/handbook"

  [menu.main.params]
  icon = "github"

[[menu.main]]
name = "Discord"
weight = 7
url = "https://discord.gg/Sv9BCTsXDh"

  [menu.main.params]
  icon = "discord"

[params.navbar]
displayTitle = true
displayLogo = true

[params.navbar.logo]
path = "images/logo.svg"
dark = "images/logo-dark.svg"
link = "/"
width = 40
height = 20

[params.editURL]
enable = true
base = "https://github.com/OSCTorino/handbook/edit/main"
